version: "3.8"

services:
  backend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-drolito123.git
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=DB
    networks:
      - etec-app-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DB
    ports:
      - "3306:3306"
    networks:
      - etec-app-network
    volumes:
      - db_data:/var/lib/mysql

  frontend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-drolito123.git
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    networks:
      - etec-app-network
    depends_on:
      - backend-app

  proxy:
    build:
      context: https://github.com/drolito123/proxy_nginx_pensado.git  # Repositorio del proxy (Nginx)
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - frontend-app
      - backend-app
    networks:
      - etec-app-network

networks:
  etec-app-network:
    external: true

volumes:
  db_data:
    external: true
